---
title: "Test title"
format: pdf
---

```{r}
#| label: import-data-and-libs

library(ggthemes)
library(tidymodels)
library(tidyverse)

death <- read_csv("data/total_death_data.csv")
lobby <- arrow::read_parquet("data/lobbyists.parquet")

# these regex filters were created manually by visiting the OpenSecrets
# website's catalog of gun lobbying groups here:
# https://www.opensecrets.org/federal-lobbying/industries/lobbyists?cycle=2024&id=Q13

gun_filter <- paste(
  "gun", "rifle", "safari club", "shoot", "crockett club", 
  "bear arms", "firearm",
  sep = "|"
)

gun_groups <- lobby |>
  filter(str_detect(client_name, regex(gun_filter, ignore_case = TRUE))) |>
  select(year, client_name, position, state) |>
  rename(state_id = "state") |>
  mutate(state = state.name[match(state_id, state.abb)]) |>
  select(-state_id)
```

```{r}
death_group <- death |>
  group_by(year) |>
  summarise(death_count = sum(gun_suicides))

gun_groups |>
  group_by(year) |>
  summarise(count = n()) |>
  left_join(death_group) |>
  pivot_longer(cols = -year, names_to = "var", values_to = "count") |>
  filter(year <= 2016) |>
  ggplot(aes(x = year, y = count, color = var)) +
  geom_line(linewidth = 2) +
  theme_fivethirtyeight() +
  scale_color_wsj() +
  facet_wrap(~var, nrow = 2, scales = "free_y")
```

```{r}
gun_group_count <- gun_groups |>
  group_by(year) |>
  summarise(lobbyist_positions = n())

mean_death_year <- death |>
  group_by(year) |>
  summarise(
    gun_suicide_rate = mean(mean_fs_s, na.rm = TRUE),
    poor_mental_rate = mean(p_poor_mental, na.rm = TRUE)
  )
```

```{r}
#| label: build-the-model

model_data <- gun_group_count |>
  left_join(mean_death_year) |>
  filter(year < 2017)

model_spec <- linear_reg() |>
  set_engine("lm")

model <- model_spec |>
  fit(
    gun_suicide_rate ~ lobbyist_positions + poor_mental_rate,
    data = model_data
  )
```

